import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const write=(p,s)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s);};
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const decode=s=>s.replaceAll('&amp;','&').replaceAll('&quot;','"').replaceAll('&#39;',"'").replace(/<[^>]+>/g,'').trim();
const csv=s=>'"'+String(s??'').replaceAll('"','""')+'"';
function files(dir='') {return fs.readdirSync(path.join(root,dir),{withFileTypes:true}).filter(d=>d.name!=='.git').flatMap(d=>d.isDirectory()?files(path.posix.join(dir,d.name)):[path.posix.join(dir,d.name)]).sort();}
function urlKey(value) {const u=new URL(value);u.hash='';for(const k of [...u.searchParams.keys()])if(k.startsWith('utm_'))u.searchParams.delete(k);return u.toString().replace(/\/$/,'');}
function doiOf(r) {return (r.doi||(/doi\.org\/(.+)/i.exec(r.url||'')?.[1])||'').replace(/^https?:\/\/(?:dx\.)?doi\.org\//i,'').trim().toLowerCase();}

const documents=[
 {id:'india-pakistan',title:'Protein Consumption and Alternative Protein Adoption in India and Pakistan',path:'research/india-pakistan/index.html',textPath:'research/india-pakistan/india-pakistan-brief.md',cutoff:'14 September 2026',kind:'Current scope brief',description:'Comparative secondary synthesis of the affordability, dietary practice, legitimacy, certification, and policy conditions that shape adoption. Proposes the comparative tests and forecast-question requirements that would follow.'},
 {id:'comparative-protein',title:'Protein Transitions Across Unequal Food Systems',path:'research/comparative-protein/index.html',textPath:'research/comparative-protein/README.md',cutoff:'13 September 2026',kind:'Comparative synthesis',description:'Protein supply, consumer adoption, public research and talent policy, and institutional capabilities. Includes country data, charts, locators, and a cited-passage ledger.'},
 {id:'ai-protein',title:'AI and the Protein Transition',path:'research/ai-protein/index.html',textPath:'research/ai-protein/literature-review.md',cutoff:'11 September 2026',kind:'Literature review',description:'Evidence connecting technical progress, adoption, displacement, animal outcomes, and policy under uncertainty. Includes an annotated library and RIS bibliography.'},
 {id:'policy-decisions',title:'Policy Evidence to Decision Table',path:'research/ai-protein/decisions.html',textPath:'research/ai-protein/policy-decisions.md',cutoff:'11 September 2026',kind:'Discussion paper',description:'Six conditional policy choices, the evidence relevant to each, and reasons to revise them. These proposals have not been evaluated or adopted.'},
 {id:'food-systems-orientation',title:'Alt-Protein and Food-Systems Orientation',path:'research/orientation/food-systems-briefing.html',textPath:'research/orientation/food-systems-briefing.md',cutoff:'5 September 2026',kind:'Earlier research briefing',description:'Technology, capital, talent, regulation, and foresight practice, with source links preserved from the original briefing.'},
 {id:'beginner-orientation',title:'Alt Protein Without the Jargon',path:'research/orientation/beginners-guide.html',textPath:'research/orientation/beginners-guide.md',cutoff:'5 September 2026',kind:'Earlier orientation guide',description:'An introduction to the production tracks, value chain, market definitions, and technical vocabulary, with private project instructions removed.'}
];
for(const d of documents)if(!fs.existsSync(path.join(root,d.path)))throw Error('Missing research document: '+d.path);
write('research/library.json',JSON.stringify({status:'AI-assisted drafts; human verification pending',documents},null,2)+'\n');

const groups=new Map();const aliases=new Map();
function add(record,occurrence) {
 if(!record.url||!/^https?:\/\//.test(record.url))return;
 const canonical=urlKey(record.url);const doi=doiOf(record);const key=aliases.get(canonical)||(doi?'doi:'+doi:'url:'+canonical);
 let g=groups.get(key);
 if(!g){g={key,title:record.title||record.label||record.url,url:record.url,doi:doi||null,type:record.type||'Public link requiring bibliographic completion',occurrences:[]};groups.set(key,g);}
 aliases.set(canonical,key);if(doi)aliases.set(urlKey('https://doi.org/'+doi),key);
 if(!g.occurrences.some(o=>o.document===occurrence.document&&o.sourceId===occurrence.sourceId&&o.recordPath===occurrence.recordPath))g.occurrences.push(occurrence);
}
let originalRecords=0;
for(const [collection,p] of [['India\u2013Pakistan current review','research/india-pakistan/source-register.json'],['Comparative protein synthesis','research/comparative-protein/source-register.json'],['AI/protein literature foundation','research/ai-protein/source-register.json']]) {
 for(const r of JSON.parse(read(p))) {
  originalRecords++;
  add(r,{collection,sourceId:r.id,recordPath:p,accessed:r.accessed||null,access:r.access||null,limitations:r.limitations||null,funding:r.funding||null,humanVerification:r.human_verification||'Pending'});
 }
}
for(const r of JSON.parse(read('research/orientation/sources.json')).sources) {
 const document=r.document.startsWith('Alt_Protein_Beginners')?'research/orientation/beginners-guide.html':'research/orientation/food-systems-briefing.html';
 const title=r.context.replace(/\s*Open source\.?\s*$/i,'').split(/\.\s+/)[0];
 add({url:r.url,title},{collection:'Orientation source link',document,sourceId:'block-'+r.block,recordPath:'research/orientation/sources.json',access:null,limitations:'Context label preserved from the original orientation; full bibliographic record requires completion.',humanVerification:'Pending; link extraction only'});
}
// Capture every public anchor in the included reports, including orientation references
// without a complete bibliography. These links are not upgraded into verified sources.
for(const p of files('research').filter(p=>p.endsWith('.html'))) {
 const s=read(p);
 for(const m of s.matchAll(/<a\b[^>]*href=["'](https?:\/\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)) {
  const url=decode(m[1]); const label=decode(m[2]);
  add({url,title:label||url},{collection:'Report source link',document:p,sourceId:null,recordPath:p,humanVerification:'Pending; link extraction only'});
 }
}
const records=[...groups.values()].sort((a,b)=>a.key.localeCompare(b.key)).map((r,i)=>({id:'SRC-'+String(i+1).padStart(3,'0'),...r}));
const catalog={description:'Inventory of public references retained in the included research. It is not a fresh source audit or an exhaustive field bibliography.',originalRegisterRecords:originalRecords,uniqueSourceIdentities:records.length,records};
write('sources/catalog.json',JSON.stringify(catalog,null,2)+'\n');
write('sources/catalog.csv','catalog_id,title,url,doi,type,used_in,human_review\n'+records.map(r=>[r.id,r.title,r.url,r.doi,r.type,r.occurrences.map(o=>o.document||o.recordPath+'#'+o.sourceId).join('; '),'Pending'].map(csv).join(',')).join('\n')+'\n');

const css=`:root{--ink:#20382d;--muted:#59695f;--line:#cdd7cc;--paper:#fbfaf5}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.7 Georgia,serif}a{color:#24563e;text-underline-offset:4px}a:hover{color:#081f13}a:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #a2692d;outline-offset:4px}.wrap{max-width:1050px;margin:auto;padding:35px 28px 80px}.top{display:flex;justify-content:space-between;gap:18px;flex-wrap:wrap;font:14px/1.6 system-ui,sans-serif;border-bottom:1px solid var(--line);padding-bottom:20px}.top nav{display:flex;gap:20px;flex-wrap:wrap}.eyebrow{font:12px/1.5 system-ui,sans-serif;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);margin-top:56px}h1{font-size:clamp(38px,6vw,68px);font-weight:normal;line-height:1.06;letter-spacing:-.03em;max-width:850px;margin:16px 0 24px}h2{font-size:28px;font-weight:normal;margin:45px 0 15px}h3{font-size:25px;font-weight:normal;line-height:1.3;margin:0 0 10px}.intro{font-size:21px;max-width:760px}.status,.meta{font:14px/1.6 system-ui,sans-serif;color:var(--muted)}.status{border-left:3px solid #7d956e;padding-left:16px;max-width:850px;margin:25px 0 42px}.research{display:grid;grid-template-columns:135px minmax(0,1fr);gap:30px;padding:27px 0;border-top:1px solid var(--line)}.research p{margin:8px 0 14px}.research .links{font:14px/1.6 system-ui,sans-serif;display:flex;gap:22px;flex-wrap:wrap}input{font:16px system-ui,sans-serif;padding:14px;width:100%;border:1px solid #829482;background:white;color:var(--ink)}label{display:block;font:14px system-ui,sans-serif;margin-bottom:8px}details{padding:20px 0;border-top:1px solid var(--line)}summary{cursor:pointer;font:16px/1.5 system-ui,sans-serif}details p,details li{overflow-wrap:anywhere}.sources-list{margin-top:25px}.source-id{font:12px system-ui,sans-serif;color:var(--muted);margin-right:9px}.source-title{display:block;margin:8px 0;font-size:20px}footer{border-top:1px solid var(--line);margin-top:48px;padding-top:22px;font:13px/1.6 system-ui,sans-serif;color:var(--muted)}[hidden]{display:none!important}@media(max-width:600px){.wrap{padding:25px 20px 55px}.research{grid-template-columns:1fr;gap:10px}.eyebrow{margin-top:35px}.intro{font-size:19px}h1{font-size:43px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}`;
const head=(title,description)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${esc(description)}"><title>${esc(title)}</title><style>${css}</style></head><body>`;
const nav=(prefix='')=>`<header class="top"><a href="${prefix}index.html">Muhammad Umar Zafar · Research</a><nav aria-label="Library"><a href="${prefix}index.html#research">Research</a><a href="${prefix}sources/index.html">Sources</a><a href="${prefix}CURRENT-SCOPE.md">Current scope</a></nav></header>`;
const footer='<footer>AI-assisted research drafts for peer and mentor feedback. Human verification pending. No institutional or mentor endorsement is implied.</footer>';
write('index.html',head('Protein research library','Research drafts, source registers, and data for peer and mentor review.')+`<div class="wrap">${nav()}<main><div class="eyebrow">Sentient Futures Project Incubator · Working research</div><h1>Protein systems,<br>evidence, and possible futures.</h1><p class="intro">A collection of research on alternative proteins, food systems, and the conditions that shape a transition. Read the studies, inspect the data, and trace the sources behind the arguments.</p><p class="status">This library holds ${documents.length} research documents and ${records.length} linked source identities. These are dated working drafts. The India–Pakistan brief is the current scope; the broader reports below are earlier background inputs.</p><p><a href="CURRENT-SCOPE.md">Read the current research scope</a> · <a href="RESEARCH-METHOD.md">Method and limitations</a></p><h2 id="research">Research in this collection</h2>${documents.map(d=>`<article class="research"><div class="meta">${esc(d.kind)}<br>${esc(d.cutoff)}</div><div><h3><a href="${d.path}">${esc(d.title)}</a></h3><p>${esc(d.description)}</p><div class="links"><a href="${d.path}">Read document →</a><a href="${d.textPath}">Repository text and notes</a></div></div></article>`).join('')}<h2>Follow the evidence</h2><p>The source catalog combines the three original registers (${originalRecords} records) with public links from the included reports. Original reference IDs, access limitations, and pending review states remain available.</p><p><a href="sources/index.html">Search the source catalog →</a> · <a href="sources/catalog.csv">Download CSV</a> · <a href="sources/catalog.json">Download JSON</a></p><p><a href="DATA-DICTIONARY.md">Understand the data</a> · <a href="CONTRIBUTING.md">Give feedback</a> · <a href="RIGHTS-AND-REUSE.md">Rights and reuse</a></p></main>${footer}</div></body></html>`);
const entries=records.map(r=>`<details data-entry><summary><span class="source-id">${r.id}</span>${esc(r.title)}</summary><p><a href="${esc(r.url)}" rel="noreferrer">Open original source</a>${r.doi?' · DOI: '+esc(r.doi):''}</p><p class="meta">${esc(r.type)} · Human verification pending</p><ul>${r.occurrences.map(o=>`<li><a href="../${esc(o.document||o.recordPath)}">${esc(o.collection)}${o.sourceId?' · '+esc(o.sourceId):''}</a>${o.accessed?' · accessed '+esc(o.accessed):''}${o.access?'<br>Access recorded in original research: '+esc(o.access):''}${o.limitations?'<br>Limitations: '+esc(o.limitations):''}</li>`).join('')}</ul></details>`).join('');
write('sources/index.html',head('Source catalog | Protein research','Search public references retained in the research collection.')+`<div class="wrap">${nav('../')}<main><div class="eyebrow">Evidence library</div><h1>Trace the sources.</h1><p class="intro">${records.length} source identities, with links back to the reports and original reference IDs.</p><p class="status">This catalog preserves the research trail. Links have not been freshly checked, and source inclusion does not establish the accuracy of a claim. Some entries contain only a public link awaiting bibliographic completion.</p><p><a href="catalog.csv">Download CSV</a> · <a href="catalog.json">Download JSON</a> · <a href="README.md">Catalog method</a></p><label for="search">Search title, source ID, DOI, or research document</label><input id="search" type="search" placeholder="For example: India, fermentation, C01" autocomplete="off"><p id="count" class="meta" aria-live="polite">${records.length} sources</p><p id="empty" hidden>No matching sources. Clear the search to see the full catalog.</p><div class="sources-list">${entries}</div></main>${footer}</div><script>const input=document.getElementById('search');const entries=[...document.querySelectorAll('[data-entry]')];input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();let n=0;for(const el of entries){el.hidden=!el.textContent.toLowerCase().includes(q);if(!el.hidden)n++;}document.getElementById('count').textContent=n+' of '+entries.length+' sources';document.getElementById('empty').hidden=n!==0;});</script></body></html>`);
const manifest=files().filter(p=>p!=='provenance/file-manifest.json').map(p=>({path:p,bytes:fs.statSync(path.join(root,p)).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')}));
write('provenance/file-manifest.json',JSON.stringify({description:'SHA-256 inventory of repository files, excluding Git metadata and this manifest itself.',files:manifest},null,2)+'\n');
console.log(JSON.stringify({documents:documents.length,originalRegisterRecords:originalRecords,sourceIdentities:records.length,files:manifest.length+1}));
